"""Tests unitaires pour scripts/mailnjoy_check.py — mock l'API Mailnjoy.

Lancer : python3 -m pytest tests/test_mailnjoy_check.py -v
"""
import sys
import json
from pathlib import Path
from unittest.mock import patch, MagicMock

import pytest

# Ajoute scripts/ au path
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts"))

from mailnjoy_check import (
    classify_response,
    check_email_mailnjoy,
    is_configured,
)


# ──────────────────────────────────────────────────────────────────────────────
# Fixtures de réponses Mailnjoy
# ──────────────────────────────────────────────────────────────────────────────
def _attr(value: bool, type_: str = "negative"):
    return {"value": value, "type": type_}


def make_response(status="VALID", category="SAFE", **flags):
    """Construit une réponse Mailnjoy v2 (wrappée dans unitaryCheck)."""
    default_flags = {
        "alias": False, "free": False, "autogenerated": False,
        "catchall": False, "disposable": False, "role": False,
        "spamtrap": False, "suspect": False, "protected": False,
    }
    default_flags.update(flags)
    return {
        "unitaryCheck": {
            "email":     "test@example.com",
            "status":    status,
            "category":  category,
            "attributs": {k: _attr(v) for k, v in default_flags.items()},
        }
    }


# ──────────────────────────────────────────────────────────────────────────────
# classify_response — table des cas
# ──────────────────────────────────────────────────────────────────────────────
class TestClassifyResponse:
    def test_valid_safe(self):
        assert classify_response(make_response("VALID", "VERY_SAFE")) == "valid"
        assert classify_response(make_response("VALID", "SAFE")) == "valid"

    def test_invalid_status(self):
        for st in ("INVALID", "INCORRECT", "SUSPECT", "FULL"):
            assert classify_response(make_response(st, "SAFE")) == "invalid"

    def test_unsafe_category(self):
        assert classify_response(make_response("VALID", "UNSAFE")) == "invalid"

    def test_spamtrap_drops_to_invalid(self):
        assert classify_response(make_response("VALID", "SAFE", spamtrap=True)) == "invalid"

    def test_disposable_drops_to_invalid(self):
        assert classify_response(make_response("VALID", "SAFE", disposable=True)) == "invalid"

    def test_risky_category(self):
        assert classify_response(make_response("VALID", "RISKY")) == "risky"

    def test_catchall_is_risky(self):
        assert classify_response(make_response("VALID", "SAFE", catchall=True)) == "risky"

    def test_role_is_risky(self):
        assert classify_response(make_response("VALID", "SAFE", role=True)) == "risky"

    def test_suspect_attribute_is_risky(self):
        assert classify_response(make_response("VALID", "SAFE", suspect=True)) == "risky"

    def test_unknown_status_defaults_to_risky(self):
        assert classify_response(make_response("WHO_KNOWS", "SAFE")) == "risky"

    def test_unwrap_when_unwrapped_payload(self):
        """Cas defensive : si la réponse n'est PAS wrappée."""
        unwrapped = {
            "status": "VALID", "category": "SAFE",
            "attributs": {k: _attr(False) for k in ("spamtrap", "disposable", "catchall", "role", "suspect")},
        }
        assert classify_response(unwrapped) == "valid"


# ──────────────────────────────────────────────────────────────────────────────
# check_email_mailnjoy — mock requests
# ──────────────────────────────────────────────────────────────────────────────
class TestCheckEmailMailnjoy:
    @patch("mailnjoy_check.is_configured", return_value=True)
    @patch("mailnjoy_check.requests.post")
    def test_200_valid(self, mock_post, _):
        mock_post.return_value = MagicMock(status_code=200, json=lambda: make_response("VALID", "SAFE"))
        r = check_email_mailnjoy("test@example.com")
        assert r["ok"] is True
        assert r["decision"] == "valid"
        assert r["status_code"] == 200

    @patch("mailnjoy_check.is_configured", return_value=True)
    @patch("mailnjoy_check.requests.post")
    def test_200_invalid(self, mock_post, _):
        mock_post.return_value = MagicMock(status_code=200, json=lambda: make_response("INVALID", "UNSAFE"))
        r = check_email_mailnjoy("bad@example.com")
        assert r["decision"] == "invalid"

    @patch("mailnjoy_check.is_configured", return_value=True)
    @patch("mailnjoy_check.requests.post")
    def test_401_config_missing(self, mock_post, _):
        mock_post.return_value = MagicMock(status_code=401, text="Read only API user")
        r = check_email_mailnjoy("test@example.com")
        assert r["ok"] is False
        assert r["decision"] == "config_missing"
        assert "401" in r["error"]

    @patch("mailnjoy_check.is_configured", return_value=True)
    @patch("mailnjoy_check.requests.post")
    def test_403_credit_exhausted(self, mock_post, _):
        mock_post.return_value = MagicMock(status_code=403, text="No credit")
        r = check_email_mailnjoy("test@example.com")
        assert r["decision"] == "credit_exhausted"

    @patch("mailnjoy_check.is_configured", return_value=True)
    @patch("mailnjoy_check.requests.post")
    def test_400_invalid_format(self, mock_post, _):
        mock_post.return_value = MagicMock(status_code=400, text="Bad email")
        r = check_email_mailnjoy("not-an-email")
        assert r["decision"] == "invalid"

    @patch("mailnjoy_check.is_configured", return_value=True)
    @patch("mailnjoy_check.time.sleep", return_value=None)  # speed up backoff
    @patch("mailnjoy_check.requests.post")
    def test_429_retry_then_success(self, mock_post, _sleep, _):
        responses = [
            MagicMock(status_code=429, headers={"Retry-After": "1"}, text="rate limited"),
            MagicMock(status_code=200, json=lambda: make_response("VALID", "SAFE")),
        ]
        mock_post.side_effect = responses
        r = check_email_mailnjoy("test@example.com", retry=3)
        assert r["decision"] == "valid"
        assert mock_post.call_count == 2

    @patch("mailnjoy_check.is_configured", return_value=True)
    @patch("mailnjoy_check.time.sleep", return_value=None)
    @patch("mailnjoy_check.requests.post")
    def test_500_retry_exhausts(self, mock_post, _sleep, _):
        mock_post.return_value = MagicMock(status_code=500, text="server err")
        r = check_email_mailnjoy("test@example.com", retry=3)
        assert r["decision"] == "error"
        assert mock_post.call_count == 3

    @patch("mailnjoy_check.is_configured", return_value=False)
    def test_not_configured(self, _):
        r = check_email_mailnjoy("test@example.com")
        assert r["decision"] == "config_missing"
        assert r["ok"] is False


# ──────────────────────────────────────────────────────────────────────────────
# Edge cases pipeline
# ──────────────────────────────────────────────────────────────────────────────
class TestPipelineEdgeCases:
    def test_classify_with_empty_attrs(self):
        # Un payload sans .attributs ne crash pas
        r = {"unitaryCheck": {"status": "VALID", "category": "SAFE"}}
        assert classify_response(r) == "valid"

    def test_classify_with_missing_status(self):
        r = {"unitaryCheck": {"category": "SAFE", "attributs": {}}}
        # status manquant -> ne match pas VALID -> defaults to risky
        assert classify_response(r) == "risky"

    def test_classify_with_string_attribute_value(self):
        # Defensive : si attributs.X.value est un string truthy
        r = make_response("VALID", "SAFE")
        r["unitaryCheck"]["attributs"]["spamtrap"] = {"value": True, "type": "negative"}
        assert classify_response(r) == "invalid"
